# Generated by Django 5.2.5 on 2025-08-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinghistory',
            old_name='discrption',
            new_name='discription',
        ),
    ]
