# Generated by Django 5.2.5 on 2025-08-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_rename_discrption_trackinghistory_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
